name: modular_core
description: A starting point for Dart libraries or applications.
version: 1.1.0
resolution: workspace

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.16.0
  go_router: ^16.0.0
  get_it: ^8.0.3
  flutter_dotenv: ^5.2.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
