name: viewmodel
description: ViewModel for Flutter
version: 1.0.0

resolution: workspace

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  logger: ^2.5.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
  build_runner: ^2.4.13
  freezed: ^3.0.6
  json_serializable: ^6.9.5
